org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

group = net.vdm

mod_id = autosellvdm
mod_name = AutoSellVDM
mod_file_name = autosellvdm
mod_version = 1.2.1

minecraft_version_out = 1.21.11
minecraft_version = 1.21.11

fabric_loader_version = 0.19.3
fabric_api_version = 0.141.4+1.21.11
mod_menu_version = 17.0.0
